dist: bionic
language: python
addons:
  apt:
    packages:
      - libgeoip-dev
matrix:
  include:
    - name: “Python 2.7 on xenial”
      python: "2.7"
      dist: xenial
    - name: “Python 2.7 on bionic”
      python: "2.7"
    - name: “Python 3.8 on bionic”
      python: "3.8"
  allow_failures:
    - python: "3.8"
install:
  - pip install flake8
  - make lint
  - pip install -r requirements_test.txt
  - pushd vendor/infogami && git pull origin master && popd;
  # if Travis is running Python 3, then
  #   refresh the git submodule ./vendor/infogami
  #   create a legacy Python for npm/node until nodejs/node#25789 is resolved
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.8" ]; then
      pushd vendor/infogami && git pull origin master && popd;
      pyenv install 2.7.14;
    fi
  - npm install
script:
  - make i18n
  - make test
